const mongoose = require('mongoose');

/**
 * RippleEvent — a post inside a Ripple's timeline ("contribution").
 *
 * `origin` matters: 'system' rows are generated by the server ("Priya joined").
 * Keeping them in the same collection but flagged means the timeline can render
 * them differently, and a system row can never be mistaken for a user's words.
 *
 * Reactions are embedded (same approach as GroupMessage.reactions) — a Ripple
 * timeline is read as a whole, so a separate collection would only add joins.
 */
const mediaSchema = new mongoose.Schema(
  {
    url: { type: String, required: true },
    thumbnailUrl: { type: String, default: null },
    mimeType: { type: String, default: null },
    width: { type: Number, default: null },
    height: { type: Number, default: null },
    duration: { type: Number, default: null },
  },
  { _id: false },
);

const reactionSchema = new mongoose.Schema(
  {
    emoji: { type: String, required: true },
    userId: { type: String, required: true },
    userName: { type: String, default: '' },
    createdAt: { type: Date, default: Date.now },
  },
  { _id: false },
);

const rippleEventSchema = new mongoose.Schema(
  {
    rippleId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Ripple',
      required: true,
      index: true,
    },
    authorId: {
      type: String, // userId String, matching Rippler/Friend/GroupChat
      required: true,
      index: true,
    },
    authorName: { type: String, default: '' },
    authorIsPage: { type: Boolean, default: false },

    origin: {
      type: String,
      enum: ['user', 'system'],
      default: 'user',
      index: true,
    },
    type: {
      type: String,
      enum: ['text', 'image', 'video', 'voice', 'location', 'system'],
      default: 'text',
    },
    body: { type: String, default: '', maxlength: 2000 },
    media: { type: [mediaSchema], default: [] },

    // Coarse label is fine here; an event location is the host's chosen spot,
    // never a participant's inferred position.
    location: {
      label: { type: String, default: null },
      lng: { type: Number, default: null },
      lat: { type: Number, default: null },
    },

    pinned: { type: Boolean, default: false, index: true },
    reactions: { type: [reactionSchema], default: [] },
    reactionCount: { type: Number, default: 0 },

    status: {
      type: String,
      enum: ['active', 'deleted'],
      default: 'active',
      index: true,
    },
    deletedAt: { type: Date, default: null },
    deletedBy: { type: String, default: null },

    idempotencyKey: {
      type: String,
      // No default:null — see the note in models/Ripple.js. A stored null would
      // collide against the partial unique index below.
      default: undefined,
    },
  },
  { timestamps: true },
);

rippleEventSchema.index({ rippleId: 1, status: 1, createdAt: -1 });
rippleEventSchema.index({ rippleId: 1, pinned: -1, createdAt: -1 });
rippleEventSchema.index({ authorId: 1, createdAt: -1 });
rippleEventSchema.index(
  { idempotencyKey: 1 },
  { unique: true, partialFilterExpression: { idempotencyKey: { $type: 'string' } } },
);

const RippleEvent = mongoose.model('RippleEvent', rippleEventSchema);

module.exports = RippleEvent;
